theme: jekyll-theme-minimal

# Name of website
title: Shj-MAO Lab

# Your name to show in the footer
author: Shj-MAO

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
